kind: Service
apiVersion: v1
metadata:
  name: udacity-page-elb
spec:
  type: LoadBalancer
  selector:
    name: udacity-page
  ports:
    - name: http
      protocol: TCP
      # ELB port
      port: 8080
      # container port
      targetPort: 8080